chore(git-hooks): use the same make targets as in the github workflow
... so we have to change our checks in just one place.

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -11,29 +11,18 @@ set -u
 GIT_ROOT=$(git rev-parse --show-toplevel)
 
 if [ -n "$(git status --porcelain)" ]; then
-    echo >&2 "Error: The working tree has uncommitted changes."
+    echo >&2 "pre-push: Error: The working tree has uncommitted changes."
     exit 1
 fi
 
-echo >&2 "pre-push: Running \`make fmt\`"
-make -C "${GIT_ROOT}" --quiet fmt
-if [ -n "$(git status --porcelain)" ]; then
-    echo >&2 "pre-push: Error: Files were modified by \"make fmt\""
-    exit 1
-fi
+echo >&2 "pre-push: Running \`make fmt/check\`"
+make -C "${GIT_ROOT}" --quiet fmt/check
 
-echo >&2 "pre-push: Running \`go mod tidy\` "
-go mod tidy
-if [ -n "$(git status --porcelain)" ]; then
-    echo >&2 "pre-push: Error: Files were modified by go mod tidy"
-    exit 1
-fi
+echo >&2 "pre-push: Running \`tidy/check\` "
+make -C "${GIT_ROOT}" --quiet tidy/check
 
-echo >&2 "pre-push: Running \`staticcheck\`"
-staticcheck ./...
-
-echo >&2 "pre-push: Running \`go vet\`"
-go vet ./...
+echo >&2 "pre-push: Running \`make lint\`"
+make -C "${GIT_ROOT}" --quiet lint 
 
 # Check if the string "DO-NOT-PUSH" is present anywhere in this
 # repository (except for this file itself)
